/**
 * Hyphenation patterns for Indonesian (Bahasa Indonesia)
 * Based on EYD V (Ejaan Bahasa Indonesia yang Disempurnakan, 2022)
 * Source: hyph-id-eydv.tex + inhyph.tex (for missing patterns)
 * 
 * Compatible with Hypher 0.2.5
 * Generated by scripts/convert-tex-patterns.js
 * 
 * Changes from original TeX source:
 * - leftmin changed from 2 to 1 (allows single-char syllables like a-ir, ha-ri)
 * - Added missing pattern 2l1q from inhyph.tex
 * - Added exception list for common words
 */
module.exports = {
  leftmin: 1,
  rightmin: 1,
  patterns: {
    "3": "e2ua1aa1ea1oe1ae1ee1ie1oi1ai1ei1ii1oi1uo1ao1eo1io1oo1uu1au1eu1iu1ou1un2gn2yk2hs2yg2hd2za1ba1ca1da1fa1ga1ha1ja1ka1la1ma1na1pa1ra1sa1ta1va1wa1xa1ya1ze1be1ce1de1fe1ge1he1je1ke1le1me1ne1pe1re1se1te1ve1we1xe1ye1zi1bi1ci1di1fi1gi1hi1ji1ki1li1mi1ni1pi1ri1si1ti1vi1wi1xi1yi1zo1bo1co1do1fo1go1ho1jo1ko1lo1mo1no1po1ro1so1to1vo1wo1xo1yo1zu1bu1cu1du1fu1gu1hu1ju1ku1lu1mu1nu1pu1ru1su1tu1vu1wu1xu1yu1z3i.",
    "4": "a2i.a2u.e2i.o2i.2ng.2ny.2b1c2b1d2b1f2b1g2b1h2b1j2b1k2b1l2b1m2b1n2b1p2b1s2b1t2b1v2b1w2c1b2c1d2c1f2c1g2c1h2c1j2c1k2c1l2c1m2c1n2c1p2c1s2c1t2c1v2c1w2d1b2d1c2d1f2d1g2d1h2d1j2d1k2d1l2d1m2d1n2d1p2d1s2d1t2d1v2d1w2f1b2f1c2f1d2f1g2f1h2f1j2f1k2f1l2f1m2f1n2f1p2f1s2f1t2f1v2f1w2g1b2g1c2g1d2g1f2g1h2g1j2g1k2g1l2g1m2g1n2g1p2g1s2g1t2g1v2g1w2h1b2h1c2h1d2h1f2h1g2h1j2h1k2h1l2h1m2h1n2h1p2h1s2h1t2h1v2h1w2j1b2j1c2j1d2j1f2j1g2j1h2j1k2j1l2j1m2j1n2j1p2j1s2j1t2j1v2j1w2k1b2k1c2k1d2k1f2k1g2k1h2k1j2k1k2k1l2k1m2k1n2k1p2k1s2k1t2k1v2k1w2l1b2l1c2l1d2l1f2l1g2l1h2l1j2l1k2l1l2l1m2l1n2l1p2l1s2l1t2l1v2l1w2m1b2m1c2m1d2m1f2m1g2m1h2m1j2m1k2m1l2m1m2m1n2m1p2m1s2m1t2m1v2m1w2n1b2n1c2n1d2n1f2n1h2n1j2n1k2n1l2n1m2n1n2n1p2n1s2n1t2n1v2n1w2p1b2p1c2p1d2p1f2p1g2p1h2p1j2p1k2p1l2p1m2p1n2p1p2p1s2p1t2p1v2p1w2r1b2r1c2r1d2r1f2r1g2r1h2r1j2r1k2r1l2r1m2r1n2r1p2r1r2r1s2r1t2r1v2r1w2r1y2s1b2s1c2s1d2s1f2s1g2s1h2s1j2s1k2s1l2s1m2s1n2s1p2s1r2s1s2s1t2s1v2s1w2t1b2t1c2t1d2t1f2t1g2t1h2t1j2t1k2t1l2t1m2t1n2t1p2t1s2t1t2t1v2t1w2v1b2v1c2v1d2v1f2v1g2v1h2v1j2v1k2v1l2v1m2v1n2v1p2v1s2v1t2v1w2w1b2w1c2w1d2w1f2w1g2w1h2w1j2w1k2w1l2w1m2w1n2w1p2w1s2w1t2w1v2x1b2x1c2x1d2x1f2x1g2x1h2x1j2x1k2x1l2x1m2x1n2x1p2x1s2x1t2x1v2x1w2z1b2z1c2z1d2z1f2z1g2z1h2z1j2z1k2z1l2z1m2z1n2z1p2z1s2z1t2z1v2z1w.me3.pe3.di3.ke3.se33an.2l1q",
    "5": "1a2i11a2u11e2i11o2i12m3br2n3br2n3cr2n3dr2n3fr2l3fr2n3gr2l3gr2n3kr2l3kr2n3pr2l3pr2m3pr2n3tr2l3tr2s3tr2m3bl2n3bl2n3cl2n3fl2n3gl2n3kl2n3pl2n3sl2n3sk2n3sp2n3st2ng1g2ng1h2ng1k2ng1n2ng1s.non3.swa3.pra3.adi33kan.3lah.3kah.3tah.3pun.3nya..bi1o.pre3.sub3.eks3.pro3.kon3.neo3i2o1nsi2onti2on",
    "6": ".be2r3.te2r3.me2n3.me2m3.pe2n3.pe2m3.pe2r3.tuna3.maha3.anti3.fo1to.ki1lo.auto3.semi3.mono3.poli3lo3gi.no3mi.is3me.",
    "7": ".me2ng3.me2ny3.pe2ng3.pe2ny3.pasca3.in3tro.trans3.multi3gra3fi.me3ter.kra3si.",
    "8": ".pseudo3",
  },
  // Exceptions: comma-separated, use \u2027 (hyphenation point) as syllable break
  // Format: "word1\u2027syll1\u2027syll2,word2\u2027syll1\u2027syll2"
  exceptions: "a\u2027ir,ha\u2027ri,o\u2027rang,gu\u2027ru,la\u2027ri,pin\u2027tar,be\u2027sar,bu\u2027lan,ta\u2027hun,can\u2027tik,pan\u2027jang,hi\u2027dung,mu\u2027rid,le\u2027her,meng\u2027er\u2027ti,me\u2027nya\u2027nyi,be\u2027re\u2027nang,ber\u2027hi\u2027tung,men\u2027jum\u2027lah\u2027kan,me\u2027nga\u2027li\u2027kan,ke\u2027mer\u2027de\u2027ka\u2027an,pe\u2027me\u2027rin\u2027tah\u2027an,ke\u2027ber\u2027sih\u2027an,ke\u2027se\u2027hat\u2027an,per\u2027ha\u2027ti\u2027an,pem\u2027bel\u2027a\u2027jar\u2027an,In\u2027do\u2027ne\u2027si\u2027a,ma\u2027kan,ja\u2027lan,me\u2027ma\u2027kan,peng\u2027a\u2027jar\u2027an,ber\u2027ja\u2027lan,mem\u2027ba\u2027gi\u2027kan,pe\u2027ni\u2027la\u2027i\u2027an"
};
