#!/usr/bin/env node
/**
 * Build browser bundle: dist/browser/id.js
 * Bundles Hypher engine + Indonesian patterns into a self-contained IIFE.
 *
 * Usage: node scripts/build-browser.cjs
 */
const esbuild = require('esbuild');
const path = require('path');
const fs = require('fs');

const distDir = path.join(__dirname, '..', 'dist', 'browser');
const entryPoint = path.join(__dirname, 'browser-entry.cjs');
const patternsFile = path.join(__dirname, '..', 'patterns', 'id.cjs');

async function build() {
  // Ensure dist/browser directory exists
  fs.mkdirSync(distDir, { recursive: true });

  // Verify patterns file exists
  if (!fs.existsSync(patternsFile)) {
    console.error(`Patterns file not found: ${patternsFile}`);
    process.exit(1);
  }

  console.log('Building dist/browser/id.js ...');

  await esbuild.build({
    entryPoints: [entryPoint],
    bundle: true,
    format: 'iife',
    globalName: 'HypherID',
    outfile: path.join(distDir, 'id.js'),
    platform: 'browser',
    target: ['es2020'],
    minify: false,
    sourcemap: false,
    define: {
      'process.env.NODE_ENV': '"production"',
    },
    banner: {
      js: `/**
 * Hypher Indonesian Hyphenation Engine (Browser Bundle)
 * Generated by scripts/build-browser.cjs
 * Includes: Hypher engine + patterns/id.cjs (EYD V, 2022)
 *
 * Usage:
 *   const h = new HypherID.Hypher(HypherID.patterns);
 *   h.hyphenate('pintar'); // ['pin', 'tar']
 */`
    },
  });

  const outFile = path.join(distDir, 'id.js');
  const stat = fs.statSync(outFile);
  console.log(`Done: ${outFile} (${(stat.size / 1024).toFixed(1)} KB)`);
}

build().catch((err) => {
  console.error(err);
  process.exit(1);
});
